services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus01
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "job=docker,container=prometheus"
        loki-relabel-config: |
          - action: labeldrop
            regex: filename|compose_project|compose_service|service_name|host         	
    depends_on:
      - loki    
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    hostname: node-exporter
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "job=docker,container=node-exporter"
        loki-relabel-config: |
          - action: labeldrop
            regex: filename|compose_project|compose_service|service_name|host	
    depends_on:
      - loki 